# when changing the version number (here or in package.json), make sure to keep the version|versionName same in both files (JFC)

vars:
  BUNDLE_ID:
    default: com.zaions.zlink
  PRODUCT_NAME:
    default: ZLink
  DISPLAY_NAME:
    default: ZLink

platforms:
  ios:
    targets:
      App:
        bundleId: $BUNDLE_ID
        version: 1.0.0
        buildNumber: 1
        productName: $PRODUCT_NAME
        displayName: $DISPLAY_NAME

  android:
    packageName: $BUNDLE_ID
    versionName: 1.0.0
    versionCode: 1
    - file: AndroidManifest.xml
        target: manifest/application
        merge: |
          <application>
            <queries>
              <package android:name="$BUNDLE_ID" />
            </queries>
          </application>
